name: pyem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.22
  - scipy>=1.10
  - pandas>=1.5
  - joblib>=1.3
  - typing-extensions>=4.6
  - tqdm
  - pytest
  - jupyterlab
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - pip
  - pip:
      - -e .   # install your local pyem package in editable mode
